### ISSUE TITLE
ページネーション時に検索結果が重複することがある

### ISSUE THREAD

**Issue by kuzukuzu** [machikoe/palette-elastic_search#45]
## 現象

ページネーションを利用したESでのクエリ実行時、
各ページ間で検索結果のドキュメントが重複することがある。

Related Issue: https://discuss.elastic.co/t/duplicate-documents-in-paginated-query-results/2094

## 原因
ページごとのクエリ実行が、それぞれ別のレプリカに対してが行われることで発生する。
検索結果順を決定するための統計情報がレプリカごとに異なるためである。

## 解決策
クエリ実行時に `preference` パラメタを指定する。
これによりクエリ実行対象のレプリカを固定することができる。

参考: https://www.elastic.co/guide/en/elasticsearch/reference/1.7/search-request-preference.html

## 議論したいこと
`preference` に何を指定するか。
以下のどちらかが良いと思っています。

- `_primary_first`
- sessionごとに異なる任意の文字列

#### メリット
- 複数ユーザ間で検索結果順序が同一となる。
- アプリケーションでは何も意識せずにESを利用できる
  + ESライブラリで固定文字列を指定すれば良いので

#### デメリット
- クエリ実行がprimary shardに集中し、負荷分散できない

#### メリット
- クエリ実行をprimary-replica間で負荷分散できる

#### デメリット
- 複数ユーザ間で検索結果順序が異なる。
- アプリケーションで管理することが増える
  + sessionごとに適当な文字列の発行
  + 検索時にアプリケーション側で、preferenceを指定する必要あり

**Comment by kuzukuzu** [comment]
個人的には `_primary_first` がいいかなと思います。
負荷分散はprimaryのshard数を増やすことで対応できますし、アプリケーション側での取り扱いも楽なので。

shard数増やす場合にre-indexingしなければいないというデメリットはありますが…。

**Comment by hyamashi** [comment]
俺も `_primary_first` がいいと思う。
re-indexingは致し方ないよね。

**Comment by kuzukuzu** [comment]
primary shard間での負荷分散とprimary-replica間での負荷分散の程度次第で、
今後primary-replica間で負荷分散を活用する方向に行くのはありかなとは思っています。

直近そこまで性能が問題になっていないため、運用の楽な `_primary_first` でいいかなという判断です。

**Comment by orvillejojo** [comment]
↑OK。CMSはpager必須なので、基本 `_primary_first` で良いでしょう。
CAP定理でいうと、
CMSの重要度は Consistency(一貫性) > Availability(可用性) だと思うので  `_primary_first` 
ユーザー側の重要度はその真逆だと思うので  `sessionごとに異なる任意の文字列（まさにuser_session）` になるでしょう
